// Generated by CoffeeScript 1.6.3
(function() {
  var API_ROOT, repo, repoName, stars, _fn, _i, _len;

  stars = $('.alert.watch_started .simple');

  API_ROOT = 'https://api.github.com/repos/';

  _fn = function(repo) {
    return $.ajax({
      url: API_ROOT + repoName
    }).done(function(response) {
      var $description;
      $description = $("<div>" + response.description + "</div>");
      return $(repo).append($description);
    });
  };
  for (_i = 0, _len = stars.length; _i < _len; _i++) {
    repo = stars[_i];
    repoName = $(repo).find('.title a:nth-child(3)').text();
    _fn(repo);
  }

}).call(this);
