// Generated by CoffeeScript 1.6.3
(function() {
  $('.pagination.ajax_paginate').hide();

  $(window).scroll(function() {
    if (($(window).scrollTop() + $(window).height()) > ($(document).height() - 200)) {
      $('.js-events-pagination')[0].click();
      return $('.pagination.ajax_paginate').hide();
    }
  });

}).call(this);
