// Generated by CoffeeScript 1.6.3
(function() {
  var link, _i, _len, _ref;

  $('.pagination.ajax_paginate').hide();

  _ref = $('.site-footer-links');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    link = _ref[_i];
    $('.dashboard-sidebar').append(link);
  }

  $(window).scroll(function() {
    if (($(window).scrollTop() + $(window).height()) > ($(document).height() - 400)) {
      $('.js-events-pagination')[0].click();
      return $('.pagination.ajax_paginate').hide();
    }
  });

}).call(this);

/*
//@ sourceMappingURL=scroll.map
*/
